#!/sbin/busybox sh
#shellcheck shell=sh
/sbin/busybox mount -t devtmpfs none /dev
/sbin/busybox mount -t proc /proc /proc
/sbin/busybox mount -t sysfs none /sys

/sbin/ubiformat /dev/mtd3 -y
/sbin/ubiattach -p /dev/mtd3

/sbin/ubimkvol /dev/ubi0 -s 19712KiB -N radio
/sbin/ubimkvol /dev/ubi0 -s 5888KiB -N efs
/sbin/ubimkvol /dev/ubi0 -s 40960KiB -N cache
/sbin/ubimkvol /dev/ubi0 -s 4096KiB -N uboot-scripts
/sbin/ubimkvol /dev/ubi0 -m -N system

# mount and unmount /radio to create UBIFS filesystem
/sbin/busybox mkdir -p /radio
/sbin/busybox mount -t ubifs ubi0:radio /radio
/sbin/busybox umount /radio

# mount and unmount /cache to create UBIFS filesystem
/sbin/busybox mkdir -p /cache
/sbin/busybox mount -t ubifs ubi0:cache /cache
/sbin/busybox umount /cache

# mount and unmount /system to create UBIFS filesystem
/sbin/busybox mkdir -p /system
/sbin/busybox mount -t ubifs ubi0:system /system
/sbin/busybox umount /system

# mount efs regardless, copy from /sdcard/efs.tar if present
/sbin/busybox mkdir -p /efs
/sbin/busybox mount -t ubifs ubi0:efs /efs

/sbin/busybox mkdir -p /mnt-tmp
/sbin/busybox mount -t vfat /dev/mmcblk0p1 /mnt-tmp

cd /mnt-tmp/backup || exit
/sbin/busybox md5sum -c efs.tar.md5

# save the exit status of md5sum
MD5RESULT=$?
if ! /sbin/busybox test $MD5RESULT; then
	echo "efs.tar could not be verified."
else
	cd /efs || exit
	/sbin/busybox tar xf /mnt-tmp/backup/efs.tar
fi

cd /

/sbin/busybox umount /efs

/sbin/flash_image boot /mnt-tmp/backup/recovery.img
/sbin/flash_image recovery /mnt-tmp/backup/recovery.img
/sbin/flash_image uboot /mnt-tmp/backup/u-boot.bin

/sbin/busybox sync
/sbin/busybox umount /mnt-tmp
/sbin/busybox umount /efs

/sbin/busybox reboot
