#!/stage1/busybox sh
export _PATH="$PATH"
export PATH=/stage1

cd /
busybox date >>/boot.txt
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

exec >> /boot.txt
exec 2>&1

if busybox grep -q bootmode=2 /proc/cmdline; then
	busybox mount /dev/block/ubiblock0_2 /ramdisk -t squashfs -o ro
else
	busybox mount /dev/block/ubiblock0_1 /ramdisk -t squashfs -o ro
fi

busybox cp -Rfp /ramdisk/* /
busybox umount /ramdisk

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -rf /stage1 /sdcard /file_contexts /efs /temp /ramdisk
busybox find /dev/* ! -name '*ubi*' -delete
export PATH="${_PATH}"
exec /init

