#!/stage1/busybox sh
export _PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

while ! busybox test -d /sys/devices/platform/s3c-sdhci.0/mmc_host/mmc0/mmc0:0001 ; do
	echo "Waiting for internal mmc..."
	busybox sleep 1
done

/lvm/sbin/lvm vgscan --mknodes --ignorelockingfailure
/lvm/sbin/lvm vgchange -aly --ignorelockingfailure

busybox mount -t ext4 /dev/lvpool/system /system
busybox mount -t ext4 /dev/lvpool/userdata /data
busybox mount -t ext4 /dev/block/mmcblk0p3 /cache

image=/stage1/ramdisk.img

busybox echo "starting bootmode detection..."
if busybox test -e /cache/.startrecovery ||
	busybox grep -q bootmode=2 /proc/cmdline || # normal mode
	busybox grep -q bootmode=5 /proc/cmdline || # xl mem
	busybox grep -q bootmode=9 /proc/cmdline; then # big mem
    # recovery boot
    busybox echo "found recovery command, preparing boot..."

	busybox rm -fr /cache/.startrecovery
	image=/stage1/ramdisk-recovery.img

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
elif ! busybox test -e /system/build.prop ; then
	# emergency boot
	busybox umount /cache
	make_ext4fs -b 4096 -g 32768 -i 8192 -I 256 -a /cache /dev/block/mmcblk0p3
	busybox mount -t ext4 /dev/block/mmcblk0p3 /cache
	busybox mkdir /cache/recovery

	busybox mount -t vfat /dev/block/mmcblk1p1 /sdcard

	UPDATE=$(busybox cat /sdcard/cyanogenmod.cfg)

	if busybox test -n "$UPDATE" && busybox test -e $UPDATE ; then
		busybox echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
	fi

	image=/stage1/ramdisk-recovery.img

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

busybox umount /cache
busybox umount /system
busybox umount /sdcard
busybox rmdir /sdcard

busybox zcat $image | busybox cpio -i


################ apply bigmem at first boot ##################################################################

bigmem=0

	if busybox [ -e /data/local/devil/bigmem ] ; then
	bigmem=`busybox cat /data/local/devil/bigmem`
		if busybox grep -q bootmode=0 /proc/cmdline; then
			if busybox [ "$bigmem" -eq 1 ] || busybox [ "$bigmem" -eq 2 ] ; then
				busybox echo $bigmem > /sys/kernel/bigmem/enable
    				busybox umount /data
				/system/bin/toolbox reboot
			fi
		fi
	fi

##############################################################################################################	

	if busybox grep -q bootmode=3 /proc/cmdline || 
		busybox grep -q bootmode=5 /proc/cmdline; then
    		busybox echo "copying XL_mem libs"
    			busybox mv /bigmem_libs/* /system/lib/
    		busybox echo 1 > /sys/kernel/bigmem/enable

	elif busybox grep -q bootmode=7 /proc/cmdline || 
		busybox grep -q bootmode=9 /proc/cmdline; then
    		busybox echo "copying XL_mem libs"
    			busybox mv /bigmem_libs/* /system/lib/
    		busybox echo 2 > /sys/kernel/bigmem/enable
	else
    		busybox echo "copying cm default libs"
    			busybox mv /default_libs/* /system/lib/
	fi
fi
busybox umount /data

if busybox grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	busybox cp lpm.rc init.rc
	busybox rm init.aries.rc
fi

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
