#!/sbin/busybox sh
#shellcheck shell=sh
/sbin/busybox mount -t devtmpfs none /dev
/sbin/busybox mount -t proc /proc /proc
/sbin/busybox mount -t sysfs none /sys

while ! /sbin/busybox test -d /sys/dev/block/179:0 ; do
	echo "Waiting for internal mmc..."
	/sbin/busybox sleep 1
done

# setup lvm volumes
/lvm/sbin/lvm lvremove -f lvpool
/lvm/sbin/lvm vgremove -f lvpool
/lvm/sbin/lvm pvremove -ffy /dev/mmcblk0p2

# force clean up
/sbin/busybox dd if=/dev/zero of=/dev/mmcblk0p2 bs=512 count=1

/lvm/sbin/lvm pvcreate /dev/mmcblk0p2
/lvm/sbin/lvm vgcreate lvpool /dev/mmcblk0p2

/lvm/sbin/lvm lvcreate -L 600M -n system lvpool
/lvm/sbin/lvm lvcreate -l 100%FREE -n userdata lvpool

# format data (/system will be formatted by updater-script)
/sbin/make_ext4fs -b 4096 -g 32768 -i 8192 -I 256 -l -16384 -a /data /dev/lvpool/userdata

/sbin/ubiformat /dev/mtd3 -y
/sbin/ubiattach -p /dev/mtd3

/sbin/ubimkvol /dev/ubi0 -s 19712KiB -N radio
/sbin/ubimkvol /dev/ubi0 -s 5888KiB -N efs
/sbin/ubimkvol /dev/ubi0 -s 40960KiB -N cache
/sbin/ubimkvol /dev/ubi0 -s 4096KiB -N uboot-scripts
/sbin/ubimkvol /dev/ubi0 -m -N system

# mount and unmount /radio to create UBIFS filesystem
/sbin/busybox mkdir -p /radio
/sbin/busybox mount -t ubifs ubi0:radio /radio
/sbin/busybox umount /radio

# mount and unmount /cache to create UBIFS filesystem
/sbin/busybox mkdir -p /cache
/sbin/busybox mount -t ubifs ubi0:cache /cache
/sbin/busybox umount /cache

# mount and unmount /system to create UBIFS filesystem
/sbin/busybox mkdir -p /system
/sbin/busybox mount -t ubifs ubi0:system /system
/sbin/busybox umount /system

# mount efs regardless, copy from /sdcard/efs.tar if present
/sbin/busybox mkdir -p /efs
/sbin/busybox mount -t ubifs ubi0:efs /efs

/sbin/busybox mkdir -p /mnt-tmp
/sbin/busybox mount -t vfat /dev/mmcblk0p1 /mnt-tmp

cd /mnt-tmp/backup || exit
/sbin/busybox md5sum -c efs.tar.md5

# save the exit status of md5sum
MD5RESULT=$?
if ! /sbin/busybox test $MD5RESULT; then
	echo "efs.tar could not be verified."
else
	cd /efs || exit
	/sbin/busybox tar xf /mnt-tmp/backup/efs.tar
fi

cd /

/sbin/busybox umount /efs

/sbin/flash_image boot /mnt-tmp/backup/recovery.img
/sbin/flash_image recovery /mnt-tmp/backup/recovery.img
/sbin/flash_image uboot /mnt-tmp/backup/u-boot.bin

/sbin/busybox sync
/sbin/busybox umount /mnt-tmp
/sbin/busybox umount /efs

/sbin/busybox reboot
