#!/stage1/busybox sh

export _PATH="$PATH"
export PATH=/stage1

cd /
busybox date >>/boot.txt
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys
busybox mount /dev/block/mmcblk0p1 /sdcard

exec >> /boot.txt
exec 2>&1

# try attaching ubi
ubiattach -m 1

# regular recovery boot
busybox echo "REGULAR BOOT" >>boot.txt

# create ubiblocks for system, ramdisk, ramdisk-recovery, vendor
ubiblock -c /dev/ubi0_0
ubiblock -c /dev/ubi0_1
ubiblock -c /dev/ubi0_2

if busybox grep -q bootmode=2 /proc/cmdline ; then
	busybox mount /dev/block/ubiblock0_2 /recovery -t squashfs -o ro
else
	busybox mount /dev/block/ubiblock0_1 /recovery -t squashfs -o ro
fi
busybox cp -Rfp /recovery/* /
busybox umount /recovery
busybox cp /boot.txt /sdcard
busybox umount /sdcard

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -rf /stage1 /sdcard /file_contexts /efs /temp /recovery
export PATH="${_PATH}"
exec /init
